// Generated by gencpp from file airsim_ros_pkgs/Land.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_LAND_H
#define AIRSIM_ROS_PKGS_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <airsim_ros_pkgs/LandRequest.h>
#include <airsim_ros_pkgs/LandResponse.h>


namespace airsim_ros_pkgs
{

struct Land
{

typedef LandRequest Request;
typedef LandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Land
} // namespace airsim_ros_pkgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros_pkgs::Land > {
  static const char* value()
  {
    return "3a122444608b7d9984b24a10fba10ac1";
  }

  static const char* value(const ::airsim_ros_pkgs::Land&) { return value(); }
};

template<>
struct DataType< ::airsim_ros_pkgs::Land > {
  static const char* value()
  {
    return "airsim_ros_pkgs/Land";
  }

  static const char* value(const ::airsim_ros_pkgs::Land&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros_pkgs::LandRequest> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::Land >
template<>
struct MD5Sum< ::airsim_ros_pkgs::LandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::Land >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::LandRequest> should match
// service_traits::DataType< ::airsim_ros_pkgs::Land >
template<>
struct DataType< ::airsim_ros_pkgs::LandRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::Land >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros_pkgs::LandResponse> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::Land >
template<>
struct MD5Sum< ::airsim_ros_pkgs::LandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::Land >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::LandResponse> should match
// service_traits::DataType< ::airsim_ros_pkgs::Land >
template<>
struct DataType< ::airsim_ros_pkgs::LandResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::Land >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_LAND_H
