// Generated by gencpp from file airsim_ros_pkgs/LandGroup.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_PKGS_MESSAGE_LANDGROUP_H
#define AIRSIM_ROS_PKGS_MESSAGE_LANDGROUP_H

#include <ros/service_traits.h>


#include <airsim_ros_pkgs/LandGroupRequest.h>
#include <airsim_ros_pkgs/LandGroupResponse.h>


namespace airsim_ros_pkgs
{

struct LandGroup
{

typedef LandGroupRequest Request;
typedef LandGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LandGroup
} // namespace airsim_ros_pkgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros_pkgs::LandGroup > {
  static const char* value()
  {
    return "1c93c56d4ef2aa094d01d2de52397e67";
  }

  static const char* value(const ::airsim_ros_pkgs::LandGroup&) { return value(); }
};

template<>
struct DataType< ::airsim_ros_pkgs::LandGroup > {
  static const char* value()
  {
    return "airsim_ros_pkgs/LandGroup";
  }

  static const char* value(const ::airsim_ros_pkgs::LandGroup&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros_pkgs::LandGroupRequest> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::LandGroup >
template<>
struct MD5Sum< ::airsim_ros_pkgs::LandGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::LandGroupRequest> should match
// service_traits::DataType< ::airsim_ros_pkgs::LandGroup >
template<>
struct DataType< ::airsim_ros_pkgs::LandGroupRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros_pkgs::LandGroupResponse> should match
// service_traits::MD5Sum< ::airsim_ros_pkgs::LandGroup >
template<>
struct MD5Sum< ::airsim_ros_pkgs::LandGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros_pkgs::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros_pkgs::LandGroupResponse> should match
// service_traits::DataType< ::airsim_ros_pkgs::LandGroup >
template<>
struct DataType< ::airsim_ros_pkgs::LandGroupResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros_pkgs::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros_pkgs::LandGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_PKGS_MESSAGE_LANDGROUP_H
