// Generated by gencpp from file airsim_ros/CirclePoses.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_CIRCLEPOSES_H
#define AIRSIM_ROS_MESSAGE_CIRCLEPOSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <airsim_ros/Circle.h>

namespace airsim_ros
{
template <class ContainerAllocator>
struct CirclePoses_
{
  typedef CirclePoses_<ContainerAllocator> Type;

  CirclePoses_()
    : header()
    , poses()  {
    }
  CirclePoses_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::airsim_ros::Circle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::airsim_ros::Circle_<ContainerAllocator> >> _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::airsim_ros::CirclePoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros::CirclePoses_<ContainerAllocator> const> ConstPtr;

}; // struct CirclePoses_

typedef ::airsim_ros::CirclePoses_<std::allocator<void> > CirclePoses;

typedef boost::shared_ptr< ::airsim_ros::CirclePoses > CirclePosesPtr;
typedef boost::shared_ptr< ::airsim_ros::CirclePoses const> CirclePosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros::CirclePoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros::CirclePoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros::CirclePoses_<ContainerAllocator1> & lhs, const ::airsim_ros::CirclePoses_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.poses == rhs.poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros::CirclePoses_<ContainerAllocator1> & lhs, const ::airsim_ros::CirclePoses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::CirclePoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::CirclePoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::CirclePoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::CirclePoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::CirclePoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::CirclePoses_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros::CirclePoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc5e78a66530b8c9f75a9952468f11a4";
  }

  static const char* value(const ::airsim_ros::CirclePoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc5e78a66530b8c9ULL;
  static const uint64_t static_value2 = 0xf75a9952468f11a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros::CirclePoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros/CirclePoses";
  }

  static const char* value(const ::airsim_ros::CirclePoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros::CirclePoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Circle[] poses\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: airsim_ros/Circle\n"
"uint8 index\n"
"geometry_msgs/Vector3 position\n"
"float64 yaw\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::airsim_ros::CirclePoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros::CirclePoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CirclePoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros::CirclePoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros::CirclePoses_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::airsim_ros::Circle_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_CIRCLEPOSES_H
