// Generated by gencpp from file airsim_ros/GPSYaw.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_GPSYAW_H
#define AIRSIM_ROS_MESSAGE_GPSYAW_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airsim_ros
{
template <class ContainerAllocator>
struct GPSYaw_
{
  typedef GPSYaw_<ContainerAllocator> Type;

  GPSYaw_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , yaw(0.0)  {
    }
  GPSYaw_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::airsim_ros::GPSYaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros::GPSYaw_<ContainerAllocator> const> ConstPtr;

}; // struct GPSYaw_

typedef ::airsim_ros::GPSYaw_<std::allocator<void> > GPSYaw;

typedef boost::shared_ptr< ::airsim_ros::GPSYaw > GPSYawPtr;
typedef boost::shared_ptr< ::airsim_ros::GPSYaw const> GPSYawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros::GPSYaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros::GPSYaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros::GPSYaw_<ContainerAllocator1> & lhs, const ::airsim_ros::GPSYaw_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros::GPSYaw_<ContainerAllocator1> & lhs, const ::airsim_ros::GPSYaw_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::GPSYaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::GPSYaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::GPSYaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::GPSYaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::GPSYaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::GPSYaw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros::GPSYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5313e55a66285d01bb2325b7f49eeadb";
  }

  static const char* value(const ::airsim_ros::GPSYaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5313e55a66285d01ULL;
  static const uint64_t static_value2 = 0xbb2325b7f49eeadbULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros::GPSYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros/GPSYaw";
  }

  static const char* value(const ::airsim_ros::GPSYaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros::GPSYaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::airsim_ros::GPSYaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros::GPSYaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSYaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros::GPSYaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros::GPSYaw_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_GPSYAW_H
