// Generated by gencpp from file airsim_ros/LandGroup.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_LANDGROUP_H
#define AIRSIM_ROS_MESSAGE_LANDGROUP_H

#include <ros/service_traits.h>


#include <airsim_ros/LandGroupRequest.h>
#include <airsim_ros/LandGroupResponse.h>


namespace airsim_ros
{

struct LandGroup
{

typedef LandGroupRequest Request;
typedef LandGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LandGroup
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::LandGroup > {
  static const char* value()
  {
    return "1c93c56d4ef2aa094d01d2de52397e67";
  }

  static const char* value(const ::airsim_ros::LandGroup&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::LandGroup > {
  static const char* value()
  {
    return "airsim_ros/LandGroup";
  }

  static const char* value(const ::airsim_ros::LandGroup&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::LandGroupRequest> should match
// service_traits::MD5Sum< ::airsim_ros::LandGroup >
template<>
struct MD5Sum< ::airsim_ros::LandGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::LandGroupRequest> should match
// service_traits::DataType< ::airsim_ros::LandGroup >
template<>
struct DataType< ::airsim_ros::LandGroupRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros::LandGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::LandGroupResponse> should match
// service_traits::MD5Sum< ::airsim_ros::LandGroup >
template<>
struct MD5Sum< ::airsim_ros::LandGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros::LandGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::LandGroupResponse> should match
// service_traits::DataType< ::airsim_ros::LandGroup >
template<>
struct DataType< ::airsim_ros::LandGroupResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::LandGroup >::value();
  }
  static const char* value(const ::airsim_ros::LandGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_LANDGROUP_H
