// Generated by gencpp from file airsim_ros/RotorPWM.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_ROTORPWM_H
#define AIRSIM_ROS_MESSAGE_ROTORPWM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace airsim_ros
{
template <class ContainerAllocator>
struct RotorPWM_
{
  typedef RotorPWM_<ContainerAllocator> Type;

  RotorPWM_()
    : header()
    , rotorPWM0(0.0)
    , rotorPWM1(0.0)
    , rotorPWM2(0.0)
    , rotorPWM3(0.0)  {
    }
  RotorPWM_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rotorPWM0(0.0)
    , rotorPWM1(0.0)
    , rotorPWM2(0.0)
    , rotorPWM3(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _rotorPWM0_type;
  _rotorPWM0_type rotorPWM0;

   typedef double _rotorPWM1_type;
  _rotorPWM1_type rotorPWM1;

   typedef double _rotorPWM2_type;
  _rotorPWM2_type rotorPWM2;

   typedef double _rotorPWM3_type;
  _rotorPWM3_type rotorPWM3;





  typedef boost::shared_ptr< ::airsim_ros::RotorPWM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros::RotorPWM_<ContainerAllocator> const> ConstPtr;

}; // struct RotorPWM_

typedef ::airsim_ros::RotorPWM_<std::allocator<void> > RotorPWM;

typedef boost::shared_ptr< ::airsim_ros::RotorPWM > RotorPWMPtr;
typedef boost::shared_ptr< ::airsim_ros::RotorPWM const> RotorPWMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros::RotorPWM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros::RotorPWM_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros::RotorPWM_<ContainerAllocator1> & lhs, const ::airsim_ros::RotorPWM_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rotorPWM0 == rhs.rotorPWM0 &&
    lhs.rotorPWM1 == rhs.rotorPWM1 &&
    lhs.rotorPWM2 == rhs.rotorPWM2 &&
    lhs.rotorPWM3 == rhs.rotorPWM3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros::RotorPWM_<ContainerAllocator1> & lhs, const ::airsim_ros::RotorPWM_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::RotorPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::RotorPWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::RotorPWM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::RotorPWM_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::RotorPWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::RotorPWM_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros::RotorPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4967432b608c06d70b17be20124fa258";
  }

  static const char* value(const ::airsim_ros::RotorPWM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4967432b608c06d7ULL;
  static const uint64_t static_value2 = 0x0b17be20124fa258ULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros::RotorPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros/RotorPWM";
  }

  static const char* value(const ::airsim_ros::RotorPWM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros::RotorPWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 rotorPWM0\n"
"float64 rotorPWM1\n"
"float64 rotorPWM2\n"
"float64 rotorPWM3\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::airsim_ros::RotorPWM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros::RotorPWM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rotorPWM0);
      stream.next(m.rotorPWM1);
      stream.next(m.rotorPWM2);
      stream.next(m.rotorPWM3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RotorPWM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros::RotorPWM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros::RotorPWM_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rotorPWM0: ";
    Printer<double>::stream(s, indent + "  ", v.rotorPWM0);
    s << indent << "rotorPWM1: ";
    Printer<double>::stream(s, indent + "  ", v.rotorPWM1);
    s << indent << "rotorPWM2: ";
    Printer<double>::stream(s, indent + "  ", v.rotorPWM2);
    s << indent << "rotorPWM3: ";
    Printer<double>::stream(s, indent + "  ", v.rotorPWM3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_ROTORPWM_H
