// Generated by gencpp from file airsim_ros/SetGPSPosition.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_SETGPSPOSITION_H
#define AIRSIM_ROS_MESSAGE_SETGPSPOSITION_H

#include <ros/service_traits.h>


#include <airsim_ros/SetGPSPositionRequest.h>
#include <airsim_ros/SetGPSPositionResponse.h>


namespace airsim_ros
{

struct SetGPSPosition
{

typedef SetGPSPositionRequest Request;
typedef SetGPSPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGPSPosition
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::SetGPSPosition > {
  static const char* value()
  {
    return "419da4302dcfe39986b1a614149a1599";
  }

  static const char* value(const ::airsim_ros::SetGPSPosition&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::SetGPSPosition > {
  static const char* value()
  {
    return "airsim_ros/SetGPSPosition";
  }

  static const char* value(const ::airsim_ros::SetGPSPosition&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::SetGPSPositionRequest> should match
// service_traits::MD5Sum< ::airsim_ros::SetGPSPosition >
template<>
struct MD5Sum< ::airsim_ros::SetGPSPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::SetGPSPosition >::value();
  }
  static const char* value(const ::airsim_ros::SetGPSPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::SetGPSPositionRequest> should match
// service_traits::DataType< ::airsim_ros::SetGPSPosition >
template<>
struct DataType< ::airsim_ros::SetGPSPositionRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::SetGPSPosition >::value();
  }
  static const char* value(const ::airsim_ros::SetGPSPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::SetGPSPositionResponse> should match
// service_traits::MD5Sum< ::airsim_ros::SetGPSPosition >
template<>
struct MD5Sum< ::airsim_ros::SetGPSPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::SetGPSPosition >::value();
  }
  static const char* value(const ::airsim_ros::SetGPSPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::SetGPSPositionResponse> should match
// service_traits::DataType< ::airsim_ros::SetGPSPosition >
template<>
struct DataType< ::airsim_ros::SetGPSPositionResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::SetGPSPosition >::value();
  }
  static const char* value(const ::airsim_ros::SetGPSPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_SETGPSPOSITION_H
