// Generated by gencpp from file airsim_ros/TakeoffGroup.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_TAKEOFFGROUP_H
#define AIRSIM_ROS_MESSAGE_TAKEOFFGROUP_H

#include <ros/service_traits.h>


#include <airsim_ros/TakeoffGroupRequest.h>
#include <airsim_ros/TakeoffGroupResponse.h>


namespace airsim_ros
{

struct TakeoffGroup
{

typedef TakeoffGroupRequest Request;
typedef TakeoffGroupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeoffGroup
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::TakeoffGroup > {
  static const char* value()
  {
    return "1c93c56d4ef2aa094d01d2de52397e67";
  }

  static const char* value(const ::airsim_ros::TakeoffGroup&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::TakeoffGroup > {
  static const char* value()
  {
    return "airsim_ros/TakeoffGroup";
  }

  static const char* value(const ::airsim_ros::TakeoffGroup&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::TakeoffGroupRequest> should match
// service_traits::MD5Sum< ::airsim_ros::TakeoffGroup >
template<>
struct MD5Sum< ::airsim_ros::TakeoffGroupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TakeoffGroup >::value();
  }
  static const char* value(const ::airsim_ros::TakeoffGroupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TakeoffGroupRequest> should match
// service_traits::DataType< ::airsim_ros::TakeoffGroup >
template<>
struct DataType< ::airsim_ros::TakeoffGroupRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TakeoffGroup >::value();
  }
  static const char* value(const ::airsim_ros::TakeoffGroupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::TakeoffGroupResponse> should match
// service_traits::MD5Sum< ::airsim_ros::TakeoffGroup >
template<>
struct MD5Sum< ::airsim_ros::TakeoffGroupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TakeoffGroup >::value();
  }
  static const char* value(const ::airsim_ros::TakeoffGroupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TakeoffGroupResponse> should match
// service_traits::DataType< ::airsim_ros::TakeoffGroup >
template<>
struct DataType< ::airsim_ros::TakeoffGroupResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TakeoffGroup >::value();
  }
  static const char* value(const ::airsim_ros::TakeoffGroupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_TAKEOFFGROUP_H
