// Generated by gencpp from file airsim_ros/TopicHz.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_TOPICHZ_H
#define AIRSIM_ROS_MESSAGE_TOPICHZ_H

#include <ros/service_traits.h>


#include <airsim_ros/TopicHzRequest.h>
#include <airsim_ros/TopicHzResponse.h>


namespace airsim_ros
{

struct TopicHz
{

typedef TopicHzRequest Request;
typedef TopicHzResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TopicHz
} // namespace airsim_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::airsim_ros::TopicHz > {
  static const char* value()
  {
    return "685d1f21c0a32ce2836c18711bcaeaff";
  }

  static const char* value(const ::airsim_ros::TopicHz&) { return value(); }
};

template<>
struct DataType< ::airsim_ros::TopicHz > {
  static const char* value()
  {
    return "airsim_ros/TopicHz";
  }

  static const char* value(const ::airsim_ros::TopicHz&) { return value(); }
};


// service_traits::MD5Sum< ::airsim_ros::TopicHzRequest> should match
// service_traits::MD5Sum< ::airsim_ros::TopicHz >
template<>
struct MD5Sum< ::airsim_ros::TopicHzRequest>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TopicHz >::value();
  }
  static const char* value(const ::airsim_ros::TopicHzRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TopicHzRequest> should match
// service_traits::DataType< ::airsim_ros::TopicHz >
template<>
struct DataType< ::airsim_ros::TopicHzRequest>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TopicHz >::value();
  }
  static const char* value(const ::airsim_ros::TopicHzRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::airsim_ros::TopicHzResponse> should match
// service_traits::MD5Sum< ::airsim_ros::TopicHz >
template<>
struct MD5Sum< ::airsim_ros::TopicHzResponse>
{
  static const char* value()
  {
    return MD5Sum< ::airsim_ros::TopicHz >::value();
  }
  static const char* value(const ::airsim_ros::TopicHzResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::airsim_ros::TopicHzResponse> should match
// service_traits::DataType< ::airsim_ros::TopicHz >
template<>
struct DataType< ::airsim_ros::TopicHzResponse>
{
  static const char* value()
  {
    return DataType< ::airsim_ros::TopicHz >::value();
  }
  static const char* value(const ::airsim_ros::TopicHzResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_TOPICHZ_H
