// Generated by gencpp from file airsim_ros/TopicHzRequest.msg
// DO NOT EDIT!


#ifndef AIRSIM_ROS_MESSAGE_TOPICHZREQUEST_H
#define AIRSIM_ROS_MESSAGE_TOPICHZREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airsim_ros
{
template <class ContainerAllocator>
struct TopicHzRequest_
{
  typedef TopicHzRequest_<ContainerAllocator> Type;

  TopicHzRequest_()
    : get(0)  {
    }
  TopicHzRequest_(const ContainerAllocator& _alloc)
    : get(0)  {
  (void)_alloc;
    }



   typedef int64_t _get_type;
  _get_type get;





  typedef boost::shared_ptr< ::airsim_ros::TopicHzRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_ros::TopicHzRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TopicHzRequest_

typedef ::airsim_ros::TopicHzRequest_<std::allocator<void> > TopicHzRequest;

typedef boost::shared_ptr< ::airsim_ros::TopicHzRequest > TopicHzRequestPtr;
typedef boost::shared_ptr< ::airsim_ros::TopicHzRequest const> TopicHzRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_ros::TopicHzRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_ros::TopicHzRequest_<ContainerAllocator1> & lhs, const ::airsim_ros::TopicHzRequest_<ContainerAllocator2> & rhs)
{
  return lhs.get == rhs.get;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_ros::TopicHzRequest_<ContainerAllocator1> & lhs, const ::airsim_ros::TopicHzRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_ros::TopicHzRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_ros::TopicHzRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_ros::TopicHzRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a514c24c167567fafb0a99dffb52d0a";
  }

  static const char* value(const ::airsim_ros::TopicHzRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a514c24c167567fULL;
  static const uint64_t static_value2 = 0xafb0a99dffb52d0aULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_ros/TopicHzRequest";
  }

  static const char* value(const ::airsim_ros::TopicHzRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 get\n"
;
  }

  static const char* value(const ::airsim_ros::TopicHzRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.get);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopicHzRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_ros::TopicHzRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_ros::TopicHzRequest_<ContainerAllocator>& v)
  {
    s << indent << "get: ";
    Printer<int64_t>::stream(s, indent + "  ", v.get);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_ROS_MESSAGE_TOPICHZREQUEST_H
