
(cl:in-package :asdf)

(defsystem "airsim_ros-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geographic_msgs-msg
               :geometry_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "Altimeter" :depends-on ("_package_Altimeter"))
    (:file "_package_Altimeter" :depends-on ("_package"))
    (:file "AngleRateThrottle" :depends-on ("_package_AngleRateThrottle"))
    (:file "_package_AngleRateThrottle" :depends-on ("_package"))
    (:file "Battery" :depends-on ("_package_Battery"))
    (:file "_package_Battery" :depends-on ("_package"))
    (:file "CarControls" :depends-on ("_package_CarControls"))
    (:file "_package_CarControls" :depends-on ("_package"))
    (:file "CarState" :depends-on ("_package_CarState"))
    (:file "_package_CarState" :depends-on ("_package"))
    (:file "Circle" :depends-on ("_package_Circle"))
    (:file "_package_Circle" :depends-on ("_package"))
    (:file "CirclePoses" :depends-on ("_package_CirclePoses"))
    (:file "_package_CirclePoses" :depends-on ("_package"))
    (:file "Environment" :depends-on ("_package_Environment"))
    (:file "_package_Environment" :depends-on ("_package"))
    (:file "GPSYaw" :depends-on ("_package_GPSYaw"))
    (:file "_package_GPSYaw" :depends-on ("_package"))
    (:file "GimbalAngleEulerCmd" :depends-on ("_package_GimbalAngleEulerCmd"))
    (:file "_package_GimbalAngleEulerCmd" :depends-on ("_package"))
    (:file "GimbalAngleQuatCmd" :depends-on ("_package_GimbalAngleQuatCmd"))
    (:file "_package_GimbalAngleQuatCmd" :depends-on ("_package"))
    (:file "PoseCmd" :depends-on ("_package_PoseCmd"))
    (:file "_package_PoseCmd" :depends-on ("_package"))
    (:file "RotorPWM" :depends-on ("_package_RotorPWM"))
    (:file "_package_RotorPWM" :depends-on ("_package"))
    (:file "TreePoses" :depends-on ("_package_TreePoses"))
    (:file "_package_TreePoses" :depends-on ("_package"))
    (:file "VelCmd" :depends-on ("_package_VelCmd"))
    (:file "_package_VelCmd" :depends-on ("_package"))
    (:file "VelCmdGroup" :depends-on ("_package_VelCmdGroup"))
    (:file "_package_VelCmdGroup" :depends-on ("_package"))
  ))